// explore tab
export const LOAD_EXPLORE='LOAD_EXPLORE'
export const LOAD_CATEGORIES = "LOAD_CATEGORIES"
export const LOAD_MORE="LOAD_MORE"

//wishlist
export const LOAD_WISHLIST = "LOAD_WISHLIST"
export const REMOVE_ITEM_WISHLIST = "REMOVE_ITEM_WISHLIST"

//cart
export const LOAD_CART="LOAD_CART"
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART"
export const ADD_ITEM_CART = "ADD_ITEM_CART"
export const INCREASE_QUANTITY = "INCREASE_QUANTITY"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"

